return {
	"glepnir/dashboard-nvim",
	dependencies = "nvim-tree/nvim-web-devicons",
	event = "VimEnter",
	config = function()
		require("dashboard").setup({
			theme = "doom",
			config = {
				header = {
					[[]],
					[[]],
					[[]],
					[[]],
					[[]],
					[[]],
					[[                                            ,--,    ,--,                                       ]],
					[[                                          ,--.'|  ,--.'|                           .--.,       ]],
					[[              ,----,                      |  | :  |  | :                         ,--.'  \      ]],
					[[            .'   .`|                      :  : '  :  : '                         |  | /\/      ]],
					[[         .'   .'  .'   ,---.     ,--.--.  |  ' |  |  ' |      ,---.     ,--.--.  :  : :        ]],
					[[       ,---, '   ./   /     \   /       \ '  | |  '  | |     /     \   /       \ :  | |-       ]],
					[[       ;   | .'  /   /    /  | .--.  .-. ||  | :  |  | :    /    /  | .--.  .-. ||  : :/|      ]],
					[[       `---' /  ;--,.    ' / |  \__\/: . .'  : |__'  : |__ .    ' / |  \__\/: . .|  |  .'      ]],
					[[         /  /  / .`|'   ;   /|  ," .--.; ||  | '.'|  | '.'|'   ;   /|  ," .--.; |'  : '        ]],
					[[       ./__;     .' '   |  / | /  /  ,.  |;  :    ;  :    ;'   |  / | /  /  ,.  ||  | |        ]],
					[[       ;   |  .'    |   :    |;  :   .'   \  ,   /|  ,   / |   :    |;  :   .'   \  : \        ]],
					[[       `---'         \   \  / |  ,     .-./---`-'  ---`-'   \   \  / |  ,     .-./  |,'        ]],
					[[                      `----'   `--`---'                      `----'   `--`---'   `--'          ]],
					[[]],
					[[]],
					[[]],
					[[]],
					[[]],
					[[]],
				},
				center = {
					{
						icon = " ",
						desc = "Open projects",
						action = "Telescope projects",
						key = "p",
					},
					{
						icon = " ",
						desc = "Old files",
						action = "Telescope oldfiles",
						key = "f",
					},
					{
						icon = " ",
						desc = "Run current",
						action = "ene!",
						key = "c",
					},
					{
						icon = "󱇧 ",
						desc = "Edit keymap",
						action = "edit ~/.config/nvim/lua/zealleaf/keymap.lua",
						key = "b",
					},
					{
						icon = "󱇧 ",
						desc = "Edit gitconfig",
						action = "edit ~/.gitconfig",
						key = "g",
					},
					{
						icon = "󱇧 ",
						desc = "Edit project history",
						action = "edit ~/.local/share/nvim/project_nvim/project_history",
						key = "h",
					},
				},
				footer = { [[]], [[]], [[code as life]] },
			},
		})
	end,
}
